# Generated by Django 5.2.15 on 2026-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_shelf_shelfshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('BOOK_ADDED', 'Book Added'), ('BOOK_UPDATED', 'Book Updated'), ('BOOK_STATUS_CHANGED', 'Status Changed'), ('BOOK_LENT', 'Book Lent'), ('BOOK_RETURNED', 'Book Returned'), ('SHELF_SHARED', 'Shelf Shared'), ('COLLABORATOR_ROLE_CHANGED', 'Role Changed'), ('COLLABORATOR_REMOVED', 'Collaborator Removed')], max_length=30),
        ),
    ]
